/**
 * Created by elliottgreaves on 12/02/15.
 */
(function($){
    $('body').eemjiiRuckus({});
}(jQuery));


/*
small
 <p>Even the smallest of stores need Wi-Fi today.  It may be simply to build a hotspot for customers in a coffee shop, but it may be for something more sophisticated such as processing credit card transactions away from the till, or being able to check what stock is available in the back room. Whatever you needs, you need Wi-Fi that works, isn’t difficult to set up, and most importantly, is safe and secure for the user.</p><p>Why is choosing the right Wi-Fi so important even for a small business? Because once you have it, you, and your customers, will come to rely on it even more in the future.</p><p>Simply Smarter Wireless allows you to move and grow from;</p><ul><li>secure credit transactions from wireless terminals, and</li><li>providing simple and secure customer hotspots, to</li><li>digital signage showing promotions</li><li>discrete video surveillance</li><li>stock checking without leaving the customer</li></ul><p>For the smaller store, often a single access point in the back office is enough to provide coverage from front of store to back, and support tens of users, but sometimes you need to cover a couple of floors and two or more access points are required. With the right Wi-Fi ,processing credit card transactions can easily be done in a PCI compliant way, and running more sophisticated things like shop video surveillance is easy</p><p>Remember,  61 % of retailers say that their customers spend more time in store since they installed Wi-Fi (source /GR DeviceSpace 2014) and 50% spend more money. That’s why choosing the right Wi-Fi is so important.</p>

 medium
 <p>From a single large store to hundreds of smaller boutiques across an entire country, Wi-Fi is the easiest way to connect customers and staff to the information they need to enable a sale. Imagine a store where sales staff never leave a customer to check if something is in stock, or where they can order out-of-stock items for next day home delivery while standing at the display. Imagine a store where customers don’t have to queue at a till to pay.</p><p>Ruckus Wireless is a market leader in Wi-Fi for mid-market retailers. Our solutions are simple to deploy, sold and supported by a huge choice of specialist resellers, and uses the smartest technology to ensure the best connection across the whole sales floor and back office.</p><p>With Wi-Fi in store, staff can better service your customer’s better, and you can start thinking about how you can</p><ul><li>Use location based services solutions - such as Ruckus SPoT™ - to review your footfall and see how people move around your store:<br><ul><li>Change your window display and analyse how many more people come into the store than just walk past</li><li>Match your highest margin products to the areas where your customers go most.</li></ul></li><li>Reward loyal customers with target promotions – something that nearly ¾ of all customers say they are happy to receive</li><li>Understand more about your demographics and how your store is used at different times and on different days of the week.</li></ul><p>“Almost every new consumer product today has an embedded Wi-Fi capability. To effectively demonstrate and sell these products, customers want to actually see and understand how to use them in a live environment. The Ruckus system, with its integrated adaptive antenna array technology, is simply in a different league and has helped increase in-store sales” Tim Pearce – Hughes Electrical (UK)</p>

large
 */